services:
  database:
    image: postgres:17
    container_name: compute_service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compute_service
    ports:
      - "5432:5432"
