spring:
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/compute_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cache:
    type: simple
  data:
    redis:
      host: localhost # Dirección de Redis
      port: 6379 # Puerto de Redis

  cloud:
    gateway:
      routes:
        - id: rate_limit_route
          uri: http://localhost:8080 # Ruta de destino
          predicates:
            - Path=/api/** # Aplica rate limiting a rutas que empiecen con /api/
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@limitResolver}"
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
