spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/compute_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple

server:
  port: 8080
